### ISSUE TITLE
BFC、GFC 、FFC、

### ISSUE THREAD

**Issue by qinhualian** [qinhualian/qinhualian.github.io#2]
## BFC Block Formatting Context 块级格式化上下文
BFC，就是一个与世隔绝的独立区域，不会互相影响
> ### 触发BFC的条件

- body根元素
- 设置浮动，不包括none
- 设置定位，absoulte或者fixed
- 行内块显示模式，inline-block
- 设置overflow，即hidden，auto，scroll
- 表格单元格，table-cell
- 弹性布局，flex

> ### 解决问题

- #### 解决外边距的塌陷问题（垂直塌陷）

```ts
<div class="hello"> <div></div> <div></div> </div>

.hello div {
  width: 100px;
  height: 100px;
  background: pink;
  margin: 100px;
}
```
![image](https://user-images.githubusercontent.com/73522318/237019069-5de44aa8-8480-4aff-83be-777942e94e21.png)

这里间距期望是200px但是因为margin塌陷只有100px

- #### 解决父子嵌套塌陷
```html
  <div class="hello">
    <div class="c"></div>
  </div>
```
```ts
.hello {
  background: pink;
  width: 300px;
  height: 300px;
}
.child {
  width: 100px;
  height: 100px;
  background: red;
  margin-top: 100px;
}
```
![image](https://user-images.githubusercontent.com/73522318/237021317-168cae4b-6dc4-4a75-a626-c0292c4bee30.png)   ![image](https://user-images.githubusercontent.com/73522318/237021077-fda1e1dd-7f0a-47a1-9d65-0400aff9d5fc.png)

- ####  当浮动产生影响的时候，可以利用BFC来清除浮动的影响
```html
    <div class="hello">
    <div class="son"></div>
    <div class="son"></div>
    <div class="son"></div>
  </div>
```
```css
.hello {
  width: 300px;
  background: red;
}
.son {
  width: 90px;
  height: 50px;
  background: blue;
  border: 1px solid #000;
  float: left;
}
```
父元素没有设置高度，元素设置浮动以后，会完全从文档流中脱离，不再占用文档流的位置，将无法撑起父元素的高度，使父元素高度丢失。
![image](https://user-images.githubusercontent.com/73522318/237026562-6902b92d-80fb-455e-87a6-205a465701ce.png)   ![image](https://user-images.githubusercontent.com/73522318/237026577-9d181142-fd39-4102-b4bc-9eabc4dc67f0.png)

解决办法最好是在父元素加上伪元素
```
.hello::after {
  content: "";
  display: block;
  clear: both; // 清除浮动
}
```
其他办法: 父元素添加高度、父元素也浮动、父元素absolute 、父元素overflow: hidden 都有副作用

- ####  BFC可以阻止标准流元素被浮动元素覆盖
```html
    <div class="red"></div>
    <div class="blue"></div>
```
```css
.red {
  width: 100px;
  height: 100px;
  background: red;
  float:left;
}
.blue {
  width: 300px;
  height: 300px;
  background: blue;
}
```

![image](https://user-images.githubusercontent.com/73522318/237023017-63e31152-5e38-4ac9-aa0b-502bca39bfc8.png)   ![image](https://user-images.githubusercontent.com/73522318/237022850-fe0e36e8-ae92-475e-b4ab-65362a16ba02.png)

## GFC(GridLayout Formatting Contexts) 网格布局格式化上下文

元素设置display值为grid的时候，此元素将会获得一个独立的渲染区域。GFC将改变传统的布局模式，他将让布局从一维布局变成了二维布局。简单的说，有了GFC之后，布局不再局限于单个维度了。这个时候你要实现类似九宫格，拼图之类的布局效果显得格外的容易。

## FFC布局(Flex Formatting Contexts)弹性格式化上下文
