### ISSUE TITLE
水平垂直居中

### ISSUE THREAD

**Issue by qinhualian** [qinhualian/qinhualian.github.io#4]
## html
```
 <div class="hello">
    <div class="son"></div>
  </div>
```

## 我最常用弹性布局
```css
.hello {
  display: flex;
  justify-content: center;
  align-items: center;
}

```
## 巧妙用法

```css
.hello {
  display: flex;
}
.son {
  margin: auto;
}
```

##  绝对定位 + transform
```css
.hello {
  position:relative;
}
.son {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

## grid布局
```css
.hello {
  display: grid;
}
.son {
  align-self: center; /*设置单元格内容的垂直位置*/
  justify-self: center; /*设置单元格内容的水平位置*/
}

```
